# logistic regression -> classification problem
1. evaluation: confusion matrix, accuracy, precision, recall, F1-score, AUC-ROC
2. sigmoid function as activation function
3. MLE is the loss function for logistic regression(prior and posterior)
# API
1. sklearn.linear_model.LogisticRegression(solver='liblinear', penalty='l2', C=1.0, max_iter=100)
2. sklearn.metrics.confusion_matrix(y_true, y_pred)
3. sklearn.metrics.accuracy_score(y_true, y_pred)
4. sklearn.metrics.precision_score(y_true, y_pred)
5. sklearn.metrics.recall_score(y_true, y_pred)
6. sklearn.metrics.f1_score(y_true, y_pred)
7. sklearn.metrics.roc_auc_score(y_true, y_score)

In [165]:
from sklearn.datasets import load_breast_cancer
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score,recall_score, f1_score, confusion_matrix
import pandas as pd

In [155]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data"
df = pd.read_csv(url)
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   1000025  698 non-null    int64
 1   5        698 non-null    int64
 2   1        698 non-null    int64
 3   1.1      698 non-null    int64
 4   1.2      698 non-null    int64
 5   2        698 non-null    int64
 6   1.3      698 non-null    str
 7   3        698 non-null    int64
 8   1.4      698 non-null    int64
 9   1.5      698 non-null    int64
 10  2.1      698 non-null    int64
dtypes: int64(10), str(1)
memory usage: 60.1 KB

   1000025  5   1  1.1  1.2  2 1.3  3  1.4  1.5  2.1
0  1002945  5   4    4    5  7  10  3    2    1    2
1  1015425  3   1    1    1  2   2  3    1    1    2
2  1016277  6   8    8    1  3   4  3    7    1    2
3  1017023  4   1    1    3  2   1  3    1    1    2
4  1017122  8  10   10    8  7  10  9    7    1    4

In [156]:

df = df.replace('?', np.nan)
df = df.dropna()
x = df.iloc[:, 1:-1]
y = df.iloc[:,-1]
y.head()

0    2
1    2
2    2
3    2
4    4
Name: 2.1, dtype: int64

In [157]:
x.head()

   5   1  1.1  1.2  2 1.3  3  1.4  1.5
0  5   4    4    5  7  10  3    2    1
1  3   1    1    1  2   2  3    1    1
2  6   8    8    1  3   4  3    7    1
3  4   1    1    3  2   1  3    1    1
4  8  10   10    8  7  10  9    7    1

In [158]:
X = np.array(x)
y = np.array(y)
print(f"y value: {np.unique(y)}")  # 应该输出 [0, 1]

#y = np.where(y == 2, 0, 1)
print(f"y value: {np.unique(y)}")  # 应该输出 [0, 1]

y value: [2 4]
y value: [2 4]

In [159]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [160]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [161]:
model_l1 = LogisticRegression(l1_ratio=1.0, solver='liblinear', C=200000000000000000.0, max_iter=100000, random_state=42)
model_l1.fit(X_train, y_train)
y_pred_l1  = lr.predict(X_test)
accuracy_score(y_test, y_pred)

0.9562043795620438

In [162]:
# L2
model_l2 = LogisticRegression(
    l1_ratio=0,
    C=10.0,
    solver='liblinear',
    max_iter=1000,
    random_state=42
)
model_l2.fit(X_train, y_train)
y_pred_l2 = model_l2.predict(X_test)
accuracy_l2 = accuracy_score(y_test, y_pred_l2)
print(f'L2 正则化准确率: {accuracy_l2:.4f}')

L2 正则化准确率: 0.9562

In [173]:
model_elastic = LogisticRegression(
    C=10.0,
    l1_ratio=0.5,
    solver='saga',
    max_iter=1000,
    random_state=42
)
model_elastic.fit(X_train, y_train)
y_pred_elastic = model_elastic.predict(X_test)
accuracy_elastic = accuracy_score(y_test, y_pred_elastic)
print(f'Elastic Net accuracy: {accuracy_elastic:.4f}')
print(f'L1 accuracy: {accuracy_score(y_test, y_pred_l1):.4f}')
print(f'L2 accuracy: {accuracy_score(y_test, y_pred_l2):.4f}')
print(f'recall_score: {recall_score(y_test, y_pred_l1, average="macro"):.4f}')
A = confusion_matrix(y_test, y_pred_l1, labels=[2, 4])
print(A)
res_precision = precision_score(y_test, y_pred_l1, pos_label=4)
print(f'precision_score: {res_precision:.4f}')
recall_score = recall_score(y_test, y_pred_l1, pos_label=4)
print(f'recall_score: {recall_score:.4f}')
f1_score = f1_score(y_test, y_pred_l1, pos_label=4)
print(f'f1_score: {f1_score:.4f}')

Elastic Net accuracy: 0.9562
L1 accuracy: 0.9562
L2 accuracy: 0.9562
recall_score: 0.9485
[[85  2]
 [ 4 46]]
precision_score: 0.9583
recall_score: 0.9200
f1_score: 0.9388